

import Navbar from "@/component/Navbar/Navbar"
import "./globals.css";
import ConditionalWrapper from "@/component/ConditionalWrapper/ConditionalWrapper";




export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ConditionalWrapper>

          {children}
        </ConditionalWrapper>
      </body>
    </html>
  );
}
